### ISSUE TITLE
could not import github.com/jackc/pgx/v5

### ISSUE THREAD

**Issue by akshzyx** [techschool/simplebank#137]
So when using latest version of sqlc and generating the db.go and model.go

I keep getting this error in both files

**db.go** file
<details>
<summary>code</summary>

```
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

type DBTX interface {
	Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, error)
	Query(context.Context, string, ...interface{}) (pgx.Rows, error)
	QueryRow(context.Context, string, ...interface{}) pgx.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}
```
</details>

error 
```
could not import github.com/jackc/pgx/v5 (cannot find package "github.com/jackc/pgx/v5" in GOROOT)
```
```
could not import github.com/jackc/pgx/v5/pgconn (cannot find package "github.com/jackc/pgx/v5/pgconn" in GOROOT)
```

same with models.go

the error
```
could not import github.com/jackc/pgx/v5/pgtype (cannot find package "github.com/jackc/pgx/v5/pgtype" in GOROOT)
```

i have them in my go.mod file but still getting this error
```
module github.com/akshzyx/simplebank

go 1.24.3

require (
	github.com/jackc/pgpassfile v1.0.0 // indirect
	github.com/jackc/pgservicefile v0.0.0-20240606120523-5a60cdf6a761 // indirect
	github.com/jackc/pgx/v5 v5.7.5 // indirect
	golang.org/x/crypto v0.37.0 // indirect
	golang.org/x/text v0.24.0 // indirect
)
```

the sqlc.yaml I used is
```
version: "2"
sql:
  - engine: "postgresql"
    queries: "./db/query/"
    schema: "./db/migration/"
    gen:
      go:
        package: "db"
        out: "./db/sqlc/"
        sql_package: "pgx/v5"
```

How to fix these import issues?
