### ISSUE TITLE
sql.Open returns *sql.DB not DBTX

### ISSUE THREAD

**Issue by KINGSABRI** [techschool/simplebank#71]
Hi, 
Thanks for the great tutorial. 

In the following code, `New` function expects `DBTX`. However, `sql.open` returns `*sql.DB` and `error` type therefore the code fails 
```go
	conn, err := sql.Open(dbDriver, dbSource)
	if err != nil {
		log.Fatal("cannot connect to db: ", err)
	}

	testQueries = New(conn) // <<--- type fails here 
```

The same issue will happen later

```go
type Store struct {
	*Queries
	db *sql.DB
}

func NewStore(db *sql.DB) *Store {
	return &Store{
		db:      db,
		Queries: New(db), // <-- here
	}
}

```

```
cannot use db (variable of type *sql.DB) as DBTX value in argument to New: *sql.DB does not implement DBTX (wrong type for method Exec)
		have Exec(query string, args ...any) (sql.Result, error)
		want Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, 
```

Thanks!

**Comment by pawlobanano** [comment]
Hi @KINGSABRI, is it still a valid issue on your side? - have you managed to fix it already?

In the line 
`_func NewStore(db *sql.DB) *Store {_` 
there is no need for a pointer for the Store interface. https://github.com/techschool/simplebank/blob/ead580874f5345dbf2d7941036a526e30d603d9e/db/sqlc/store.go#L23 I encourage you to use a static profiler - when I added '*', I immediately got an error, in my case in VSCode.

**Comment by KINGSABRI** [comment]
Hi @pawlobanano , thank you for your reply. I'm still having this issue. 

I had a look at your code, if you removed the point, you can't reference it (`&SQLStore`)

https://github.com/techschool/simplebank/blob/ead580874f5345dbf2d7941036a526e30d603d9e/db/sqlc/store.go#L23-L28

**Comment by techschool** [comment]
@KINGSABRI You can still reference it, because `Store` is just an interface, while `SQLStore` is a struct that implements the interface. They're basically 2 separate entities. 
It should be fine as long as `SQLStore` implements all methods required by the `Store` interface.
You can read more about interface here: https://gobyexample.com/interfaces
And play around with the interface here: https://go.dev/tour/methods/9

**Comment by Ultra317** [comment]
did you chose pgx/v5 in the sqlc.yaml? I have the same problem like you before
````yaml
version: "2"
sql:
  - engine: "postgresql"            #使用的数据库引擎
    queries: "./db/query"           #sql查询文件路径
    schema: "./db/migration"        #包含数据库架构和迁移文件的路径
    gen:
      go:
        package: "db"               #生成的包名
        out: "./db/sqlc"            #指定生成文件路径
        sql_package: "pgx/v5"
        emit_json_tags: true        #是否将JSON标签添加到生成的结构中
        emit_prepared_queries: false #是否生成预处理查询
        emit_exact_table_names: false #是否使用精确的表名
        # 假设表名为accouts，若为true，则models中生成的结构名称为Account，否则为Accounts
```
then i change it into
```yaml
version: "1"
packages:
  - name: "db"
    path: "./db/sqlc"
    queries: "./db/query/"
    schema: "./db/migration/"
    engine: "postgresql"
    emit_db_tags: true
    emit_prepared_queries: false
    emit_interface: false
    emit_exact_table_names: false
```
and it just works, i think it may cause by the different sql_packge use between version 1 and version 2
